### ISSUE TITLE
Italian translation not visible

### ISSUE THREAD

**Issue by anoukvlug** [OGGM/world-glacier-explorer#17]
Italian seems not to be a selectable option for me in the app, even though the Italian translation exists in the international.py file. I'm not sure why this is the case.

<img width="540" alt="Glacier_explorer_print_screen" src="https://user-images.githubusercontent.com/23718819/166430091-b38430af-e5ef-4b73-b686-a4cd7a8f46a2.png">

**Comment by fmaussion** [comment]
Thanks for the report - yes I think I need to make a new release on the official server

**Comment by anoukvlug** [comment]
Thank you for solving the issue @fmaussion!

**Comment by anoukvlug** [comment]
After the issue was solved, it now reoccurred. Both Italian and Dutch is not selectable at the moment.

**Comment by pat-schmitt** [comment]
Hi @anoukvlug, I think there was no official release since Italian and Dutch were included in the app. For context: to prevent you from publishing something that breaks the app, not everything pushed to github master is directly published on the OGGM-Edu website. Actually, on the OGGM-Edu website, you see only the official released version (currently 1.2, released Mar 2021). But you can check the current status of the app on MyBinder (click on the 'binder app dev' button in github, this shows the app as it is in master at the moment). For publishing, you must follow something like this for the glacier simulator: https://github.com/OGGM/glacier_simulator/blob/master/HOWTO_RELEASE.md. If wanted I can help with this.

**Comment by anoukvlug** [comment]
Thank you @pat-schmitt for the information and your offer to help me :) 
As there seems to be a lot of activity going on now with new languages being added etc, I will wait a little longer before starting the process and use the binder version tomorrow at the Polar Symposium (in the Netherlands).
